### ISSUE TITLE
Reproducable Linux library build

### ISSUE THREAD

**Issue by paskal** [bookingcom/bpfink#5]
There is a problem with building ebpf library as Makefile: it relies on having Kernel source code and there are no Dockerfile to do that.
Also [Makefile#34](https://github.com/bookingcom/bpfink/blob/master/pkg/ebpf/Makefile#L34) refers to `.c` files build as pre-requisite but has no instructions for building it, I believe it can be removed.

@thecrogers I believe there must be a Docker image for builds, something like `bpfink:1.0.0`: would you be so kind to share Dockerfile for it so I would be able to include it into the project?

**Comment by thecrogers** [comment]
I don’t have a dockerfile right now. I can put one together and push it up in the next few days.

**Comment by paskal** [comment]
Hi @thecrogers, have you had a chance to look into it?

**Comment by thecrogers** [comment]
I have started here:
https://github.com/bookingcom/bpfink/blob/thecrogers-docker/Dockerfile

I think it is still missing some kernel-headers lib. Will try to have a MR this week.

**Comment by paskal** [comment]
Thanks! I think the current version is almost working, only thing missing is linux headers:

```
vfs.c:1:10: fatal error: 'linux/kconfig.h' file not found
#include <linux/kconfig.h>
         ^~~~~~~~~~~~~~~~~
```

I'll look into it tomorrow.

**Comment by paskal** [comment]
How to start the build [in the branch mentioned above](https://github.com/bookingcom/bpfink/tree/thecrogers-docker):

```
docker build --tag bpfink-build .
docker run -v "$(pwd):/workspace" bpfink-build
```

The problem which I haven't resolved yet is the absence of files in ` /lib/modules/3.10.0-1127.10.1.el7.x86_64/`: I haven't figured out yet how to populate this folder, it's populated not from rpm package but in some other way. @thecrogers would you be so kind to help me make it work?

**Comment by thecrogers** [comment]
So that dir should be populated when the correct kernel-devel rpm is installed. I don’t remember what the package name is. I will try to look it up.

**Comment by paskal** [comment]
I've fixed builds for 3.10, the only thing left to be done is to add builds for 4.9, 4.14 and 4.19, and also add auto-commit of these libraries after build.

**Comment by thecrogers** [comment]
We can close this issue now correct? @paskal

**Comment by paskal** [comment]
I want to add automatic CI build of such libraries and only then resolve this one.
